title: Collective Futurecrafting
description: >- 
  Collective Futurecrafting is a wholistic system for place based and community-led transformation, weaving ancient wisdom with modern innovation to create flourishing futures for all life.
baseurl: ""
url: "https://collectivefuturecrafting.net"

author: Mathew Mytka
logo: /assets/images/logo.svg
locale: en_AU 

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  resources:
    output: true
    permalink: /resources/:title/
  authors:
    output: true
    permalink: /authors/:name/
  story_nodes:
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/collective-futurecrafting-social.jpg
  - scope:
      path: "pages"
    values:
      layout: page
  - scope:
      path: "_resources"
      type: resources
    values:
      layout: resource
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "_authors"
      type: authors
    values:
      layout: "author"

# Feed settings
feed:
  collections:
    posts:
      path: "/blog.xml"
    resources:
      path: "/resources.xml"
