title: Collective Futurecrafting
description: >- 
  Collective Futurecrafting is a wholistic system for place based and community-led transformation, weaving ancient wisdom with modern innovation to create flourishing futures for all life.
baseurl: "/collective-futurecrafting"
url: "https://m3data.github.io/collective-futurecrafting"

author: Mathew Mytka
# logo: /assets/images/logo.svg
locale: en_AU 


markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-assets

collections:
  about:
    output: true
    permalink: /:collection/:name
  craft:
    output: true
    permalink: /:collection/:name
  resources:
    output: true
    permalink: /:collection/:title/
  get-involved:
    output: true
    permalink: /:collection/:name
  story_nodes:
    output: true
  blog:
    output: true
    permalink: /blog/:title/
  authors:
    output: true
    permalink: /authors/:name/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/collective-futurecrafting-social.jpg
  - scope:
      path: ""
      type: "about"
    values:
      layout: page
  - scope:
      path: ""
      type: "craft"
    values:
      layout: page
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "get-involved"
    values:
      layout: page
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

include:
  - assets